version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  go-long:
    lang: golang-middleware
    handler: ./go-long
    image: alexellis2/go-long:latest
    environment:
      write_timeout: 5m
      read_timeout: 5m
      exec_timeout: 5m

