version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  go-long:
    lang: golang-middleware
    handler: ./go-long
    image: alexellis2/go-long:0.1.2
    environment:
      write_timeout: 3m
      read_timeout: 3m
      exec_timeout: 3m
      handler_wait_duration: 60s

configuration:
  templates:
  - name: golang-middleware

