version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  go-long:
    lang: golang-middleware
    handler: ./go-long
    image: alexellis2/go-long:0.1.3
    environment:
      write_timeout: 3m
      read_timeout: 3m
      exec_timeout: 3m
      handler_wait_duration: 60s

  node12-sleep:
    lang: node12
    handler: ./node12-sleep
    image: alexellis2/node12-sleep:0.1.0
    environment:
      write_timeout: 3m
      read_timeout: 3m
      exec_timeout: 3m

configuration:
  templates:
  - name: golang-middleware
  - name: node12

